name: Slack
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: f1-data
    required: true
  - name: webhook_url
    inputType: FreeText
    description: The webhook url to send notifications to
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: quix_function.py
